apiVersion: inference.networking.k8s.io/v1
kind: InferencePool
metadata:
  name: ${POOL_NAME}-encode
spec:
  selector:
    matchLabels:
      llm-d.ai/role: encode
  endpointPickerRef:
    name: ${EPP_NAME}-encode
    kind: Service
    port:
      number: 9002
  targetPorts:
  - number: 8000
