apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${EPP_NAME}-decode
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${EPP_NAME}-decode-binding
subjects:
- kind: ServiceAccount
  name: ${EPP_NAME}-decode
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: epp-reader
---
apiVersion: v1
kind: Service
metadata:
  name: ${EPP_NAME}-decode
  labels:
    app: ${EPP_NAME}-decode
spec:
  selector:
    app: ${EPP_NAME}-decode
  ports:
  - name: default
    protocol: TCP
    port: 9002
    targetPort: 9002
    appProtocol: http2
  - name: metrics
    protocol: TCP
    port: 9090
    targetPort: 9090
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${EPP_NAME}-decode
  labels:
    app: ${EPP_NAME}-decode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${EPP_NAME}-decode
  template:
    metadata:
      labels:
        app: ${EPP_NAME}-decode
    spec:
      serviceAccountName: ${EPP_NAME}-decode
      terminationGracePeriodSeconds: 130
      containers:
      - name: epp
        image: ${EPP_IMAGE}
        imagePullPolicy: IfNotPresent
        args:
        - --pool-name
        - "${POOL_NAME}-decode"
        - --pool-namespace
        - "${NAMESPACE}"
        - --v
        - "4"
        - --zap-encoder
        - "json"
        - --grpc-port
        - "9002"
        - --grpc-health-port
        - "9003"
        - --config-file
        - "/etc/epp/epp-config.yaml"
        - --metrics-endpoint-auth=${METRICS_ENDPOINT_AUTH}
        ports:
        - containerPort: 9002
        - containerPort: 9003
        - name: metrics
          containerPort: 9090
        livenessProbe:
          grpc:
            port: 9003
            service: envoy.service.ext_proc.v3.ExternalProcessor
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          grpc:
            port: 9003
            service: envoy.service.ext_proc.v3.ExternalProcessor
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: epp-config
          mountPath: /etc/epp
      volumes:
      - name: epp-config
        configMap:
          name: epp-config-decode
