apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: epp-reader
rules:
- apiGroups:
  - "inference.networking.x-k8s.io"
  resources:
  - "inferencepools"
  - "inferenceobjectives" # TODO: remove this in issue 1298
  - "inferencemodelrewrites"  # TODO: remove this in issue 1298
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - "inference.networking.k8s.io"
  resources:
  - "inferencepools"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - "llm-d.ai"
  resources:
  - "inferenceobjectives"
  - "inferencemodelrewrites"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - "authentication.k8s.io"
  resources:
  - "tokenreviews"
  verbs:
  - "create"
- apiGroups:
  - "authorization.k8s.io"
  resources:
  - "subjectaccessreviews"
  verbs:
  - "create"
